[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"

# Proxy all /api/* requests to the backend - eliminates CORS entirely
[[redirects]]
  from = "/api/*"
  to = "https://tickets-api.netlify.app/api/:splat"
  status = 200
  force = true

# SPA fallback - must come AFTER the API proxy
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
