services:
  - type: web
    name: tedxgju-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      # Add these in Render dashboard (don't commit secrets):
      # - SUPABASE_URL
      # - SUPABASE_SERVICE_ROLE_KEY
      # - GOOGLE_SPREADSHEET_ID
      # - GOOGLE_SERVICE_ACCOUNT_JSON
      # - EMAIL_PROVIDER
      # - EMAIL_SENDER_ADDRESS
      # - GMAIL_APP_PASSWORD
      # - PUBLIC_TICKET_BASE_URL (set to: https://tedxgju-api.onrender.com)
      # - APP_URL (set to: https://your-netlify-app.netlify.app)
